spring:

  zipkin:
    enable: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  cloud:
  
    loadbalancer:
      ribbon:
      enabled: false
    
    gateway:
    
      routes:
      - id: cliente-route
        uri: lb://service-client
        predicates:
        - Path=/cliente/**
      - id: venda-route
        uri: lb://service-vendas
        predicates:
        - Path=/vendas/**                
      - id: payment-route
        uri: lb://service-payment
        predicates:
        - Path=/payment/** 
      - id: gateway-route
        uri: lb://service-gateway
        predicates:
        - Path=/gateway/**
      - id: banco-route
        uri: lb://jdbc:h2:mem:banco-cliente
        predicates:
        - Path=/h2/**
           
      default-filters:
      - name: Retry
        args:
          retries: 4
          methods: GET, POST
          series: SERVER_ERROR
          exceptions: java.io.IOException
          backoff:
            firstBackoff: 50ms
            maxBackoff: 3000ms
            factor: 2
            basedOnPreviousValue: false 

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/           

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
          gateway:
            route:
              RouteDefinitionRouteLocator: INFO, TRACE
          