spring:

  cloud:
  
    loadbalancer:
      ribbon:
      enabled: false
    
    gateway:
    
      routes:
      - id: cliente-route
        uri: lb://SERVICECLIENT
        predicates:
        - Path=/cliente/**
      - id: gateway-route
        uri: lb://SERVICEGATEWAY
        predicates:
        - Path=/gateway/**
      - id: banco-route
        uri: lb://jdbc:h2:mem:banco-cliente
        predicates:
        - Path=/h2/**
           
      default-filters:
      - name: Retry
        args:
          retries: 4
          methods: GET, POST
          series: SERVER_ERROR
          exceptions: java.io.IOException
          backoff:
            firstBackoff: 50ms
            maxBackoff: 3000ms
            factor: 2
            basedOnPreviousValue: false 
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/           
